import requests
import json
import sys

def extract_products(text_file):
    # Ollama API endpoint
    url = "http://localhost:11434/api/chat"
    model = "qwen3-coder:30b"

    # Read the OCR text
    try:
        with open(text_file, "r", encoding="utf-8") as f:
            ocr_text = f.read()
    except FileNotFoundError:
        print(f"Error: Could not find {text_file}. Make sure you run ocr.py first!")
        sys.exit(1)

    # Prompt for structuring
    prompt = f"""
You are an expert data extraction AI.
I have OCR text from a receipt. I need you to extract the purchased products.

IMPORTANT RULES:
1. The barcode for a product is ALWAYS printed ABOVE the product name. You must match the product name to the barcode directly above it.
2. Extract only: product name, barcode, quantity, and price.
3. Return ONLY a valid JSON object. Do not include markdown formatting, explanations, or any other text. Just the raw JSON.

JSON Schema:
{{
  "products": [
    {{
      "product_name": "string",
      "barcode": "string",
      "quantity": "string",
      "price": "string"
    }}
  ]
}}

Receipt OCR Text:
{ocr_text}
"""

    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False
    }

    print(f"Sending text to Ollama ({model})... This might take a few seconds.")
    try:
        response = requests.post(url, json=payload, timeout=300)
        response.raise_for_status()
        
        result_text = response.json()["message"]["content"]
        
        # Clean markdown if present
        result_text = result_text.replace("```json", "").replace("```", "").strip()
        
        # Parse and print JSON
        data = json.loads(result_text)
        print("\nExtracted Products:")
        print(json.dumps(data, indent=4))
        
        # Save to file
        with open("final_products.json", "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        print("\nSaved extracted data to final_products.json")
            
    except Exception as e:
        print(f"Error: {e}")
        if 'response' in locals() and hasattr(response, 'text'):
            print(f"Raw response: {response.text}")
        else:
            print("Failed to get a response from Ollama. Make sure the model name is correct and Ollama is running.")

if __name__ == "__main__":
    # Point this to the txt file generated by your OCR script
    extract_products("ocr_output.txt")
